### ISSUE TITLE
Renew access token API

### ISSUE THREAD

**Issue by ruowan** [microsoft/opensource-portal#102]
I can't find renew access token API, should I need to renew a token manually when token expired.

**Comment by jeffwilcox** [comment]
Using GitHub App or the older PAT method?

**Comment by ruowan** [comment]
I use the older PAT. My app need to query MS employee profile by GithubID.  I read this doc https://github.com/microsoft/opensource-portal/blob/develop/API.md.

**Comment by jeffwilcox** [comment]
Sorry, I misunderstood and thought that you were trying to use and run this open source project.

If you're a Microsoft employee you can provide different authentication mechanisms:

- You can create a PAT at https://ossmsft.visualstudio.com (these expire)
- You can create a PAT at https://repos.opensource.microsoft.com/settings (create a new one once expired)
- If your team is running an official service or system, you can have a PAT from the opensource site "upgraded" to tie to your team instead of an individual and the expiration can be removed

You may also want to consider directly querying Kusto instead of hitting the API. More information is at https://docs.opensource.microsoft.com/tools/insights/github-insights.html
