### ISSUE TITLE
Query is too slow

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/opensource-portal#64]
Takes forever to "search" for a repo, and I wish there was a top level button labelled "My Repos".  In fact, every interaction with the site at repos.opensource.microsoft.com seems really really slow right now...

**Comment by jeffwilcox** [comment]
Agreed. A lot of this has to do with challenges working with GitHub's third-party service APIs: while a lot of the data can be cached, it can often take a while. If you can do something directly on GitHub, that's always going to be the best place to go.

The best place to actually see the 'Your repositories' view is literally the GitHub.com homepage at https://github.com. On the right side you should see this list.

We are collecting data and are aware of some dependencies that are severely impacting performance. Once issues #55 and #56 are fixed perf should improve for many operations. That work will happen in July.

Here's a sample chart we're gathering from application insights; this is the 99 percentile - so some of the worst performing data - and from this chart we have a hunting list for performance fixes. The dependency of Azure Table is a big one. There are a few dependencies, such as the GitHub API, that unfortunately we'll never be able to speed up, since it's a third-party, non-Microsoft service in a data center that is not ours.

![worstcase](https://user-images.githubusercontent.com/427913/27358380-3800df74-55cb-11e7-9846-9994bcb5a190.jpg)

For now I'll leave this issue open until we have more to report. Thanks!

**Comment by lovettchris** [comment]
Thanks for the quick response.  I'm a big fan of caching for this then.  The reason I wanted the opensource-portal to show my "my" repos is that I have a log to"other" non-work related hit repos, so having a place to quickly see and manage my "Microsoft" ones would be nice.  The insights are cool, but perhaps could be moved to separate page where I'd be more willing to wait.

**Comment by jeffwilcox** [comment]
We'll see what we can do. To be clear, the search views _are cached_; across all of the Microsoft orgs creating the cross-repo views takes about 15 minutes of processing time with GitHub. You may be able to improve performance if you go to a specific sub-org, such as Microsoft or Azure, and just search within its repos there. (the repo site endpoint/orgName/repos)

Also, if you share the name of the repo you are searching for, I can use it as part of validating whether we're improving things when we go tackle these issues.

**Comment by jeffwilcox** [comment]
@lovettchris minor update - we've taken some targeted changes and are now deploying to a Kubernetes cluster backed by much more modern cloud SKUs (zippy fast), and it's making huge improvements in performance for querying. Give it a try.

We will have more to do...

**Comment by jeffwilcox** [comment]
Closing, this should not be an issue with the latest generation TS app.
